"""Pin the demo wrapper's status-write + atexit-bypass invariants.

The wrapper script generated by `_python_script` is what actually executes
each run in its own subprocess. Before 2026-05-23, the wrapper called
`finalize_benchmark()` BEFORE `write_status("completed")`. When the SDK's
atexit subprocess.wait hung on WSL2 (Defect 2 in the aclose investigation
spec), the pipeline would write `final_report.json` cleanly but the demo
UI would be stuck on `status=running` forever because the completed-status
write never reached disk.

The fix: write the completed status FIRST (right after the pipeline returns
non-zero or zero), then best-effort `finalize_benchmark`, then `os._exit`
to bypass atexit hooks that could wedge the runner process.

This test compiles the rendered wrapper string to assert (1) it is still
valid Python after the edit, and (2) the ordering invariant + os._exit
escape hatch are present where they belong.
"""

from __future__ import annotations

from pathlib import Path

from backend.services.events.live_runs import StartRunRequest, _python_script


def _render() -> str:
    request = StartRunRequest()  # all defaults
    return _python_script(
        request,
        project_id="prj_test_ordering_inv",
        runs_root=Path("/tmp/openresearch_test_runs"),
        uploaded_paper={"path": "/tmp/x.pdf", "fileName": "x.pdf"},
    )


class TestWrapperRendering:
    def test_rendered_wrapper_is_valid_python(self) -> None:
        # The wrapper is generated via f-string with doubled braces — easy to
        # break with a stray single brace. Compile catches that immediately.
        script = _render()
        compile(script, "<demo-wrapper>", "exec")  # raises SyntaxError on bad render


class TestStatusOrderingInvariant:
    """The 'stuck running' bug (prj_6b9acbfd8afcd789) was a hang BETWEEN the
    pipeline returning success and the wrapper writing `completed`. Pin the
    fix shape so we can't regress it.
    """

    def test_completed_status_is_written_before_finalize_benchmark(self) -> None:
        script = _render()
        completed_idx = script.find('write_status("completed"')
        # Skip past the function definition (`def finalize_benchmark():` line)
        # and find the actual CALL inside the try-block. The call appears
        # AFTER the `try:` keyword and on its own line indented.
        try_idx = script.find('try:\n    if config["uploaded_paper"]')
        assert try_idx != -1, "wrapper must have a try-block for the pipeline call"
        # The call we care about appears after the try-block opens.
        finalize_call_idx = script.find("\n    finalize_benchmark()", try_idx)
        # If the fix landed, the call is now indented one extra level (inside
        # an inner try). Accept either indentation; the call must exist.
        if finalize_call_idx == -1:
            finalize_call_idx = script.find("\n        finalize_benchmark()", try_idx)
        assert completed_idx != -1, "wrapper must call write_status('completed')"
        assert finalize_call_idx != -1, (
            "wrapper must call finalize_benchmark() inside the pipeline try-block"
        )
        # The completed-status write must come BEFORE the finalize_benchmark call.
        assert completed_idx < finalize_call_idx, (
            "write_status('completed') must appear before finalize_benchmark() "
            "in the success path — a hang in finalize_benchmark or atexit must "
            "not leave the UI stuck on 'running'."
        )

    def test_finalize_benchmark_is_wrapped_in_try_except(self) -> None:
        # If finalize_benchmark raises, the run is already marked completed —
        # the exception must not propagate up and trigger the 'failed' branch.
        script = _render()
        # The success block must have a try/except wrapping finalize_benchmark.
        # Find the chunk between the completed-write and the outer except.
        completed_idx = script.find('write_status("completed"')
        next_except_idx = script.find("except Exception as exc", completed_idx)
        chunk = script[completed_idx:next_except_idx]
        assert "try:" in chunk and "except Exception:" in chunk, (
            "finalize_benchmark() call must be wrapped in try/except so its "
            "failure does not revert the already-written 'completed' status."
        )
        assert "finalize_benchmark()" in chunk

    def test_finally_block_calls_os_exit(self) -> None:
        # atexit hooks from claude-agent-sdk can hang in subprocess.wait on
        # WSL2 after SIGKILL — bypass with os._exit so the runner process
        # actually terminates and the parent can reap it.
        script = _render()
        assert "finally:" in script, "wrapper must have a finally block"
        assert "_os_exit._exit(" in script, (
            "wrapper must call os._exit in the finally block — bypassing "
            "atexit hooks so a hung SDK subprocess cleanup cannot keep the "
            "runner process alive after status is on disk."
        )

    def test_exit_code_follows_final_status(self) -> None:
        # On `completed` status the wrapper should exit 0; on anything else
        # (failed, running-still, missing) it should exit 1 so process
        # reapers and CI can distinguish success from failure.
        script = _render()
        assert "_os_exit._exit(0 if _final_status == \"completed\" else 1)" in script, (
            "wrapper exit code must follow the on-disk status — 0 on "
            "completed, 1 otherwise."
        )

    def test_failure_path_also_reaches_finally(self) -> None:
        # If the pipeline raises, the wrapper writes 'failed' and falls
        # through to finally. The old code had `raise` in the except branch;
        # that triggered Python's default unhandled-exception path which
        # ran atexit (the hang). Removing the bare `raise` (or relying on
        # the finally os._exit to fire first) is the fix.
        script = _render()
        # Find the failed-status write and verify nothing between it and the
        # finally block re-raises in a way that bypasses os._exit.
        failed_idx = script.find('write_status("failed"')
        finally_idx = script.find("finally:", failed_idx)
        assert failed_idx != -1 and finally_idx != -1
        between = script[failed_idx:finally_idx]
        # The bare `raise` from the old code is gone — only `import traceback`
        # and `print_exc()` are between the failed-status write and finally.
        assert "    raise\n" not in between, (
            "the bare 'raise' in the except branch is what made the old "
            "code trigger atexit hangs — keep it out so finally's os._exit "
            "fires cleanly."
        )
