"""Phase 2B — preflight IMPORT smoke (the executing half of preflight "TDD").

The static AST gate (``preflight_ast.scan_code_dir``) reads the code; this runs an
actual cheap *test* INSIDE the sandbox before the GPU training command: it imports
every third-party dependency the agent's code declares and fails loudly if one does
not resolve. That catches the ``ModuleNotFoundError`` class (e.g. ``import
matplotlib`` with no requirements entry) in SECONDS on CPU, instead of after a GPU
pod spins up and training starts.

Design (robust + low-false-positive):
  * It probes ONLY the *imported dependency roots* (AST-collected ``import X`` /
    ``from X import …``), NEVER the agent's own modules — so it can never trigger
    "training on import" side effects. Importing a missing dep IS a real bug, so the
    false-positive rate is essentially zero.
  * It runs with ``CUDA_VISIBLE_DEVICES=""`` (never touches the GPU) and inherits the
    sandbox's isolation (network/mem/fs controls, hard command timeout).
  * Gated behind ``REPROLAB_PREFLIGHT_SMOKE`` (default OFF) — opt-in, since even an
    import executes code; the sandbox is the isolation boundary.

The emitted script is self-contained (stdlib only) because it runs in the sandbox
where ``backend`` is not importable — mirroring the ``gpu_cell_runner`` / ``rubric_
guard`` copyable-helper pattern, but generated rather than copied.
"""
from __future__ import annotations

import os
from pathlib import Path

# A command carrying this marker short-circuits the sandbox command loop on failure
# (skip the remaining training commands) — see _execute_in_sandbox.
MARKER = "# reprolab:preflight-smoke"

_EMITTED_NAME = "_preflight_smoke.py"

# Self-contained, stdlib-only. Runs in the sandbox CWD == code/.
SMOKE_SCRIPT = r'''#!/usr/bin/env python3
"""Auto-generated by ReproLab preflight_smoke — do not edit. Probes that every
third-party dependency the agent's code imports actually resolves. Exits 3 on any
failure so the harness skips the GPU training command. Never imports the agent's own
modules (no training-on-import)."""
import ast
import importlib
import json
import os
import pathlib
import sys

os.environ.setdefault("CUDA_VISIBLE_DEVICES", "")  # never touch the GPU

HERE = pathlib.Path(__file__).resolve().parent
_SELF = pathlib.Path(__file__).name

# Local modules/packages — never probed (avoid executing the agent's own code).
_local = set()
for _p in HERE.iterdir():
    if _p.suffix == ".py":
        _local.add(_p.stem)
    elif _p.is_dir() and any(_p.glob("*.py")):
        _local.add(_p.name)

# 1. Collect top-level dependency roots from every .py via AST (no execution).
roots = set()
for py in sorted(HERE.rglob("*.py")):
    if py.name == _SELF:
        continue
    try:
        tree = ast.parse(py.read_text(encoding="utf-8"))
    except Exception:
        continue  # SyntaxError etc. is the static AST gate's job, not ours
    # MODULE-LEVEL imports only (direct children of the module body) — these are the
    # imports that actually execute on ``import <module>``. Deliberately skip imports
    # nested in functions/classes (lazy imports) and inside ``try``/``if`` blocks
    # (ImportError-guarded optionals): a copied harness helper (search_qa_env.py,
    # alfworld_env.py) lazy-imports faiss/datasets/alfworld INSIDE functions, so a
    # non-SDAR paper that never calls them must NOT be flagged as missing them. A
    # missed lazy import just degrades to the pre-smoke behaviour (caught at run time,
    # repairable) — far cheaper than the false positive of installing alfworld for an
    # optimizer paper.
    for node in tree.body:
        if isinstance(node, ast.Import):
            for alias in node.names:
                roots.add(alias.name.split(".")[0])
        elif isinstance(node, ast.ImportFrom):
            if node.level == 0 and node.module:  # absolute imports only
                roots.add(node.module.split(".")[0])

# 2. Probe each third-party root (skip locals + __future__).
failures = []
probed = []
for r in sorted(roots):
    if not r or r in _local or r == "__future__":
        continue
    probed.append(r)
    if r == "backend":
        # In-repo harness import (`from backend.agents.rlm... import X`): the sandbox is
        # FLAT, so `backend` is not importable. The copied helpers live next to train.py
        # — import them BARE: `from provenance import emit_provenance`, `from rubric_guard
        # import assert_metrics_schema`, `from cell_scheduler import ...`.
        failures.append({
            "module": "backend",
            "error_type": "SandboxImportError",
            "error": ("in-repo 'backend.*' import is unavailable in the flat sandbox; "
                      "rewrite to a bare import of the copied helper, e.g. 'from provenance "
                      "import emit_provenance' (NOT 'from backend.agents.rlm.provenance import ...')"),
        })
        continue
    try:
        importlib.import_module(r)
    except BaseException as exc:  # catch SystemExit/KeyboardInterrupt from odd deps too
        failures.append({
            "module": r,
            "error_type": type(exc).__name__,
            "error": str(exc)[:300],
        })

result = {"ok": not failures, "probed": probed, "failures": failures}
try:
    (HERE / "preflight_smoke_result.json").write_text(json.dumps(result, indent=2), encoding="utf-8")
except OSError:
    pass

if failures:
    print("PREFLIGHT IMPORT SMOKE FAILED: " + json.dumps(failures), file=sys.stderr)
    sys.exit(3)
print("PREFLIGHT IMPORT SMOKE OK — %d dependency root(s) resolve" % len(probed))
'''


def is_enabled() -> bool:
    """True when ``REPROLAB_PREFLIGHT_SMOKE`` is truthy (default OFF — opt-in)."""
    return os.environ.get("REPROLAB_PREFLIGHT_SMOKE", "").strip().lower() in (
        "1", "true", "yes", "on",
    )


def emit(code_dir: Path) -> Path:
    """Write the self-contained smoke script into ``code_dir``; return its path."""
    target = code_dir / _EMITTED_NAME
    target.write_text(SMOKE_SCRIPT, encoding="utf-8")
    return target


def smoke_command(code_dir: Path) -> str:
    """Return the sandbox command that runs the smoke (carrying :data:`MARKER`).

    Resolves a working interpreter at run time (``python3`` then ``python``) so the
    step is robust across the runpod image (``python``/``python3`` present) and the
    local per-run venv. GPU is hidden for the probe.
    """
    code = str(code_dir)
    return (
        f'sh -c \'cd "{code}" && P=$(command -v python3 || command -v python) && '
        f'CUDA_VISIBLE_DEVICES="" "$P" {_EMITTED_NAME}\'  {MARKER}'
    )


__all__ = ["MARKER", "SMOKE_SCRIPT", "is_enabled", "emit", "smoke_command"]
