"""Knowledge channel: generate curated helpers + verify sub-agent emitted code."""
from __future__ import annotations

import ast
import hashlib
import json
import re
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Any

KNOWLEDGE_CHANNEL_VERSION: int = 1


class Severity(str, Enum):
    STRICT = "strict"
    PREFERRED = "preferred"
    ADVISORY = "advisory"


@dataclass(frozen=True)
class CuratedFact:
    id: str
    family: str  # "dataset" | "env" | "optimizer" | "download"
    severity: Severity
    helper_name: str
    helper_body: str        # full def source
    required_import: str    # exact line train.py must contain
    banned_literals: tuple[str, ...] = ()
    helper_hash: str = ""   # sha256 of helper_body; filled by from_recipes / factory


@dataclass(frozen=True)
class Violation:
    fact_id: str
    severity: Severity
    kind: str  # "missing_import" | "shadowed_helper" | "banned_literal" | "helper_hash_mismatch"
    detail: str


def _make_hash(body: str) -> str:
    return hashlib.sha256(body.encode("utf-8")).hexdigest()


def _fact_from_recipe(r: dict) -> CuratedFact | None:
    """Build a CuratedFact from a DatasetRecipe dict. Return None if helper_body empty."""
    helper_body = (r.get("helper_body") or "").strip()
    if not helper_body:
        return None
    helper_name = (r.get("helper_name") or "").strip()
    recipe_id = (r.get("recipe_id") or "").strip()
    severity_raw = (r.get("severity") or "preferred").lower()
    try:
        severity = Severity(severity_raw)
    except ValueError:
        severity = Severity.PREFERRED
    banned = tuple(b for b in (r.get("banned_literals") or ()) if b)
    required_import = f"from _openresearch_curated import {helper_name}"
    return CuratedFact(
        id=recipe_id or f"dataset.{helper_name}",
        family="dataset",
        severity=severity,
        helper_name=helper_name,
        helper_body=helper_body,
        required_import=required_import,
        banned_literals=banned,
        helper_hash=_make_hash(helper_body),
    )


def from_recipes(recipes: list[dict]) -> list[CuratedFact]:
    """Map dataset_recipes.find_recipes_in_text() output to CuratedFact list.

    Skip recipes whose helper_body is empty (means no curated helper yet).
    """
    facts: list[CuratedFact] = []
    for r in recipes:
        fact = _fact_from_recipe(r)
        if fact is not None:
            facts.append(fact)
    return facts


def render_helper_module(facts: list[CuratedFact]) -> tuple[str, dict]:
    """Return (module_source, manifest_dict).

    Module source assembles all helper_body strings into one Python file with a
    module-level header comment naming the KNOWLEDGE_CHANNEL_VERSION. Manifest
    is JSON-serializable and carries version + per-fact metadata.
    """
    header = (
        f"# _openresearch_curated.py — auto-generated by OpenResearch baseline_knowledge\n"
        f"# knowledge_channel_version={KNOWLEDGE_CHANNEL_VERSION}\n"
        f"# DO NOT EDIT — this file is regenerated on each run.\n"
    )
    bodies = "\n\n".join(f.helper_body for f in facts)
    module_source = header + "\n" + bodies + "\n"

    manifest_facts = [
        {
            "id": f.id,
            "helper_name": f.helper_name,
            "required_import": f.required_import,
            "banned_literals": list(f.banned_literals),
            "severity": f.severity.value,
            "helper_hash": f.helper_hash,
        }
        for f in facts
    ]
    manifest = {
        "version": KNOWLEDGE_CHANNEL_VERSION,
        "facts": manifest_facts,
    }
    return module_source, manifest


def write_curated_artifacts(code_dir: Path, facts: list[CuratedFact]) -> dict:
    """Write code_dir/_openresearch_curated.py and code_dir/_openresearch_curated_manifest.json.

    Returns the manifest dict. If facts is empty, write neither file and return
    {"version": KNOWLEDGE_CHANNEL_VERSION, "facts": []}.
    """
    empty_manifest: dict = {"version": KNOWLEDGE_CHANNEL_VERSION, "facts": []}
    if not facts:
        return empty_manifest

    module_source, manifest = render_helper_module(facts)
    curated_py = code_dir / "_openresearch_curated.py"
    curated_manifest = code_dir / "_openresearch_curated_manifest.json"

    curated_py.write_text(module_source, encoding="utf-8")
    curated_manifest.write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    return manifest


def verify_emitted_code(train_py_path: Path, manifest: dict, code_dir: Path) -> list[Violation]:
    """AST-parse train.py and check curated-knowledge constraints.

    For each fact in manifest checks:
      - missing_import: required_import not present in train.py source.
      - shadowed_helper: train.py defines a function with helper_name at module level.
      - banned_literal: any banned_literal appears in train.py source (string literals + raw text).
      - helper_hash_mismatch: _openresearch_curated.py hash doesn't match manifest fact hash.

    Returns list of Violation (empty = pass). Severity is on each Violation so
    the caller decides which violations block execution.
    """
    violations: list[Violation] = []
    facts_list = manifest.get("facts") or []
    if not facts_list:
        return violations

    # Read train.py source.
    if not train_py_path.exists():
        for fact_entry in facts_list:
            severity = _parse_severity(fact_entry.get("severity", "preferred"))
            violations.append(Violation(
                fact_id=fact_entry.get("id", "unknown"),
                severity=severity,
                kind="missing_import",
                detail=f"train.py not found at {train_py_path}",
            ))
        return violations

    source = train_py_path.read_text(encoding="utf-8", errors="replace")

    # Try AST parse; fall back to source-only checks if parse fails.
    try:
        tree = ast.parse(source)
        ast_ok = True
    except SyntaxError:
        tree = None
        ast_ok = False

    # Collect top-level function names (for shadowed_helper check).
    top_level_funcs: set[str] = set()
    if ast_ok and tree is not None:
        for node in ast.iter_child_nodes(tree):
            if isinstance(node, ast.FunctionDef):
                top_level_funcs.add(node.name)

    # Collect all string constants in AST (for banned_literal check).
    ast_string_constants: set[str] = set()
    if ast_ok and tree is not None:
        for node in ast.walk(tree):
            if isinstance(node, ast.Constant) and isinstance(node.value, str):
                ast_string_constants.add(node.value)

    # Check helper module hash.
    curated_py = code_dir / "_openresearch_curated.py"
    if curated_py.exists():
        actual_module_source = curated_py.read_text(encoding="utf-8", errors="replace")
    else:
        actual_module_source = None

    for fact_entry in facts_list:
        fact_id = fact_entry.get("id", "unknown")
        helper_name = fact_entry.get("helper_name", "")
        required_import = fact_entry.get("required_import", "")
        banned_literals = fact_entry.get("banned_literals") or []
        expected_hash = fact_entry.get("helper_hash", "")
        severity = _parse_severity(fact_entry.get("severity", "preferred"))

        # missing_import check — flexible: handles "from _openresearch_curated import a, b".
        import_present = _check_import_present(source, helper_name)
        if not import_present:
            violations.append(Violation(
                fact_id=fact_id,
                severity=severity,
                kind="missing_import",
                detail=(
                    f"train.py must contain: from _openresearch_curated import {helper_name}"
                ),
            ))

        # shadowed_helper check — top-level function with same name.
        if helper_name and helper_name in top_level_funcs:
            violations.append(Violation(
                fact_id=fact_id,
                severity=severity,
                kind="shadowed_helper",
                detail=(
                    f"train.py defines a top-level function named {helper_name!r} "
                    f"which shadows the curated helper — remove the local definition"
                ),
            ))

        # banned_literal check — raw source substring + AST string constants.
        for lit in banned_literals:
            if lit in source:
                violations.append(Violation(
                    fact_id=fact_id,
                    severity=severity,
                    kind="banned_literal",
                    detail=(
                        f"train.py contains banned literal {lit!r} — "
                        f"use the curated helper instead"
                    ),
                ))
                break  # one violation per fact for banned literals is enough
            if any(lit in s for s in ast_string_constants):
                violations.append(Violation(
                    fact_id=fact_id,
                    severity=severity,
                    kind="banned_literal",
                    detail=(
                        f"train.py AST contains banned literal {lit!r} — "
                        f"use the curated helper instead"
                    ),
                ))
                break

        # helper_hash_mismatch check.
        if expected_hash:
            if actual_module_source is None:
                violations.append(Violation(
                    fact_id=fact_id,
                    severity=severity,
                    kind="helper_hash_mismatch",
                    detail=(
                        f"_openresearch_curated.py is missing from {code_dir} "
                        f"but manifest expects helper {helper_name!r}"
                    ),
                ))
            else:
                # Re-hash the current curated module to detect tampering.
                # We hash the portion of the file that corresponds to this helper.
                # Since all helpers are in one file, we check the whole file hash
                # against the per-fact hash stored at write time.
                # The per-fact helper_hash is sha256(helper_body), and the rendered
                # module may add a header — we re-extract the body and compare.
                actual_body = _extract_helper_body(actual_module_source, helper_name)
                if actual_body is None:
                    violations.append(Violation(
                        fact_id=fact_id,
                        severity=severity,
                        kind="helper_hash_mismatch",
                        detail=(
                            f"_openresearch_curated.py does not define {helper_name!r} "
                            f"or the definition could not be extracted"
                        ),
                    ))
                else:
                    actual_hash = _make_hash(actual_body)
                    if actual_hash != expected_hash:
                        violations.append(Violation(
                            fact_id=fact_id,
                            severity=severity,
                            kind="helper_hash_mismatch",
                            detail=(
                                f"_openresearch_curated.py helper {helper_name!r} hash "
                                f"mismatch: expected {expected_hash[:12]}… got {actual_hash[:12]}…"
                            ),
                        ))

    return violations


def violations_to_repair_context(violations: list[Violation]) -> dict:
    """Shape violations as a dict compatible with repair_context.preflight_violations.

    Uses the shape that patch-mode in primitives.py expects:
    {"preflight_violations": [{"detail": "...", "severity": "...", "kind": "..."}]}
    """
    return {
        "preflight_violations": [
            {
                "detail": v.detail,
                "severity": v.severity.value,
                "kind": v.kind,
                "fact_id": v.fact_id,
            }
            for v in violations
        ]
    }


# ---------------------------------------------------------------------------
# Private helpers
# ---------------------------------------------------------------------------


def _parse_severity(s: str) -> Severity:
    try:
        return Severity(s.lower())
    except ValueError:
        return Severity.PREFERRED


def _check_import_present(source: str, helper_name: str) -> bool:
    """Return True if train.py imports helper_name from _openresearch_curated."""
    # Match: from _openresearch_curated import <identifiers>
    # The helper_name must appear as a whole identifier token (word boundary).
    pattern = re.compile(
        r"^from\s+_openresearch_curated\s+import\s+(.+)$",
        re.MULTILINE,
    )
    for m in pattern.finditer(source):
        imports_str = m.group(1)
        # Split on commas and strip each identifier
        imported_names = {tok.strip() for tok in imports_str.split(",")}
        if helper_name in imported_names:
            return True
    return False


def _extract_helper_body(module_source: str, helper_name: str) -> str | None:
    """Extract the function body text for helper_name from module_source.

    Returns the raw source of the def block (from 'def <name>' to EOF or
    next top-level def/class). Returns None if not found.
    """
    lines = module_source.splitlines(keepends=True)
    start_idx: int | None = None
    for i, line in enumerate(lines):
        if re.match(rf"^def\s+{re.escape(helper_name)}\s*\(", line):
            start_idx = i
            break
    if start_idx is None:
        return None

    # Collect lines until next top-level def/class or EOF.
    body_lines: list[str] = []
    for line in lines[start_idx:]:
        body_lines.append(line)
        # Stop at next top-level definition (not the first line).
        if len(body_lines) > 1 and re.match(r"^(def|class)\s+", line):
            body_lines.pop()  # don't include the next definition's header
            break

    return "".join(body_lines).rstrip()
