#!/usr/bin/env bash
# azure_wire_env.sh — Map Bicep stack outputs → backend env vars (.env.azure)
#
# Usage:
#   scripts/azure_wire_env.sh <resource-group> [stack-name=openresearch-l1] [out=.env.azure]
#
# After running, inspect the generated file:
#   cat .env.azure
# Then merge into your working .env:
#   grep -v '^#' .env.azure >> .env     # append non-comment lines
#   # or: source .env.azure in your shell for one-off runs
#
# NOTE: OPENRESEARCH_AZURE_BASE_IMAGE is NOT an infra output.
# It is the ACR cell image tag built by scripts/azure_build_cell_image.sh.
# Set it separately after building the image.
#
# Subscription used in this project:
#   51008c59-ebf4-4699-8f2c-896724144d42  (AIONIC / rg-sciartgen-external)

set -euo pipefail

# ─── Args ─────────────────────────────────────────────────────────────────────
RG="${1:-}"
STACK_NAME="${2:-openresearch-l1}"
OUT="${3:-.env.azure}"

if [[ -z "$RG" ]]; then
  echo "ERROR: resource-group argument is required." >&2
  echo "Usage: $0 <resource-group> [stack-name=openresearch-l1] [out=.env.azure]" >&2
  exit 1
fi

# ─── Dependency checks ────────────────────────────────────────────────────────
if ! command -v az &>/dev/null; then
  echo "ERROR: 'az' (Azure CLI) is not installed or not on PATH." >&2
  echo "Install: https://learn.microsoft.com/en-us/cli/azure/install-azure-cli" >&2
  exit 1
fi

if ! command -v jq &>/dev/null; then
  echo "ERROR: 'jq' is not installed or not on PATH." >&2
  echo "Install: apt-get install jq  /  brew install jq" >&2
  exit 1
fi

# ─── Auth check ───────────────────────────────────────────────────────────────
if ! az account show &>/dev/null; then
  echo "ERROR: Not logged in to Azure CLI. Run: az login" >&2
  exit 1
fi

# ─── Fetch stack outputs ──────────────────────────────────────────────────────
echo "Fetching outputs from stack '${STACK_NAME}' in resource group '${RG}' ..."
OUTPUTS_JSON=$(az stack group show \
  --resource-group "$RG" \
  --name "$STACK_NAME" \
  --query outputs \
  -o json 2>/dev/null) || {
  echo "ERROR: Stack '${STACK_NAME}' not found in resource group '${RG}'." >&2
  echo "  Check: az stack group list --resource-group ${RG} -o table" >&2
  exit 1
}

if [[ "$OUTPUTS_JSON" == "null" || -z "$OUTPUTS_JSON" ]]; then
  echo "ERROR: Stack '${STACK_NAME}' has no outputs (deployment may be incomplete)." >&2
  exit 1
fi

# Helper: extract a required output value by key; errors clearly if missing.
_out() {
  local key="$1"
  local val
  val=$(echo "$OUTPUTS_JSON" | jq -r --arg k "$key" '.[$k].value // empty')
  if [[ -z "$val" ]]; then
    echo "ERROR: Stack output '${key}' is missing or null." >&2
    echo "  Available outputs: $(echo "$OUTPUTS_JSON" | jq -r 'keys[]' | tr '\n' ' ')" >&2
    exit 1
  fi
  echo "$val"
}

# ─── Extract values ───────────────────────────────────────────────────────────
CLUSTER_NAME=$(_out "clusterName")
ACR_LOGIN_SERVER=$(_out "acrLoginServer")
STORAGE_ACCOUNT=$(_out "storageAccountNameOut")
BLOB_CONTAINER=$(_out "blobContainerNameOut")
FILES_SHARE=$(_out "filesShareNameOut")

# The deployed GPU node pool name: first entry of gpuPools array output.
# This is the single-source fix — no hand-guessing of pool names.
NODE_POOL_NAME=$(echo "$OUTPUTS_JSON" | jq -r '.gpuPools.value[0].name // empty')
if [[ -z "$NODE_POOL_NAME" ]]; then
  echo "WARNING: Stack output 'gpuPools[0].name' not found; falling back to 'gpua100'." >&2
  NODE_POOL_NAME="gpua100"
fi

# Derive region from the resource group (not a Bicep output, but unambiguous).
REGION=$(az group show --name "$RG" --query location -o tsv 2>/dev/null || echo "westus3")

# ─── Write output file ────────────────────────────────────────────────────────
cat > "$OUT" <<EOF
# Generated by scripts/azure_wire_env.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')
# Source: stack '${STACK_NAME}' in resource group '${RG}'
# DO NOT commit this file — it reflects live infra state and may contain
# environment-specific values. Add .env.azure to .gitignore.

OPENRESEARCH_AZURE_RESOURCE_GROUP=${RG}
OPENRESEARCH_AZURE_REGION=${REGION}
OPENRESEARCH_AZURE_AKS_CLUSTER=${CLUSTER_NAME}
OPENRESEARCH_AZURE_ACR_LOGIN_SERVER=${ACR_LOGIN_SERVER}
OPENRESEARCH_AZURE_STORAGE_ACCOUNT=${STORAGE_ACCOUNT}
OPENRESEARCH_AZURE_BLOB_CONTAINER=${BLOB_CONTAINER}
OPENRESEARCH_AZURE_FILES_SHARE=${FILES_SHARE}
OPENRESEARCH_AZURE_NODE_POOL_NAME=${NODE_POOL_NAME}

# OPENRESEARCH_AZURE_BASE_IMAGE is NOT set here.
# Build and pin the cell image with scripts/azure_build_cell_image.sh, then
# add the printed OPENRESEARCH_AZURE_BASE_IMAGE=... line to your .env.
EOF

echo ""
echo "Written: ${OUT}"
echo ""
echo "Next steps:"
echo "  1. Review:  cat ${OUT}"
echo "  2. Merge:   grep -v '^#' ${OUT} | grep -v '^$' >> .env"
echo "  3. Build cell image and pin:"
echo "              scripts/azure_build_cell_image.sh ${ACR_LOGIN_SERVER}"
echo "     Then append the printed OPENRESEARCH_AZURE_BASE_IMAGE=... to .env."
