#!/usr/bin/env python3
"""Auto-generated by ReproLab preflight_smoke — do not edit. Probes that every
third-party dependency the agent's code imports actually resolves. Exits 3 on any
failure so the harness skips the GPU training command. Never imports the agent's own
modules (no training-on-import)."""
import ast
import importlib
import json
import os
import pathlib
import sys

os.environ.setdefault("CUDA_VISIBLE_DEVICES", "")  # never touch the GPU

HERE = pathlib.Path(__file__).resolve().parent
_SELF = pathlib.Path(__file__).name

# Local modules/packages — never probed (avoid executing the agent's own code).
_local = set()
for _p in HERE.iterdir():
    if _p.suffix == ".py":
        _local.add(_p.stem)
    elif _p.is_dir() and any(_p.glob("*.py")):
        _local.add(_p.name)

# 1. Collect top-level dependency roots from every .py via AST (no execution).
roots = set()
for py in sorted(HERE.rglob("*.py")):
    if py.name == _SELF:
        continue
    try:
        tree = ast.parse(py.read_text(encoding="utf-8"))
    except Exception:
        continue  # SyntaxError etc. is the static AST gate's job, not ours
    # MODULE-LEVEL imports only (direct children of the module body) — these are the
    # imports that actually execute on ``import <module>``. Deliberately skip imports
    # nested in functions/classes (lazy imports) and inside ``try``/``if`` blocks
    # (ImportError-guarded optionals): a copied harness helper (search_qa_env.py,
    # alfworld_env.py) lazy-imports faiss/datasets/alfworld INSIDE functions, so a
    # non-SDAR paper that never calls them must NOT be flagged as missing them. A
    # missed lazy import just degrades to the pre-smoke behaviour (caught at run time,
    # repairable) — far cheaper than the false positive of installing alfworld for an
    # optimizer paper.
    for node in tree.body:
        if isinstance(node, ast.Import):
            for alias in node.names:
                roots.add(alias.name.split(".")[0])
        elif isinstance(node, ast.ImportFrom):
            if node.level == 0 and node.module:  # absolute imports only
                roots.add(node.module.split(".")[0])

# 2. Probe each third-party root (skip locals + __future__).
failures = []
probed = []
for r in sorted(roots):
    if not r or r in _local or r == "__future__":
        continue
    probed.append(r)
    try:
        importlib.import_module(r)
    except BaseException as exc:  # catch SystemExit/KeyboardInterrupt from odd deps too
        failures.append({
            "module": r,
            "error_type": type(exc).__name__,
            "error": str(exc)[:300],
        })

result = {"ok": not failures, "probed": probed, "failures": failures}
try:
    (HERE / "preflight_smoke_result.json").write_text(json.dumps(result, indent=2), encoding="utf-8")
except OSError:
    pass

if failures:
    print("PREFLIGHT IMPORT SMOKE FAILED: " + json.dumps(failures), file=sys.stderr)
    sys.exit(3)
print("PREFLIGHT IMPORT SMOKE OK — %d dependency root(s) resolve" % len(probed))
